services:

  app:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - ./.env
    volumes:
      - ./webapp:/app/webapp
    networks:
      our-network:
        ipv4_address: 172.32.0.2
    ports:
      - "4444:4444"


networks:
  our-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16
