package constants

import "webapp/utils/types"

/*
 * Green: #30c93d
 * GreenBlue: #3dbd90
 * DarkBlue: #2181bb
 * LightBlue: #06bbe8
 * Silver: #888888
 * Red: #dd1515
 * Orange: #ed670e
 * Yellow: #eda30e
 * Lilac: #e95ec2
 * Pink: #ff7ea4
 */

var PeriodicTable = []types.Element{
	{Name: "Hydrogen", Symbol: "H", AtomicNumber: 1, Group: 1, Period: 1, Category: "Nonmetal", Color: "#30c93d", ColNum: 1, RowNum: 1},
	{Name: "Helium", Symbol: "He", AtomicNumber: 2, Group: 18, Period: 1, Category: "Noble Gas", Color: "#06bbe8", ColNum: 18, RowNum: 1},
	{Name: "Lithium", Symbol: "Li", AtomicNumber: 3, Group: 1, Period: 2, Category: "Alkali Metal", Color: "#eda30e", ColNum: 1, RowNum: 2},
	{Name: "Beryllium", Symbol: "Be", AtomicNumber: 4, Group: 2, Period: 2, Category: "Alkaline Earth Metal", Color: "#ed670e", ColNum: 2, RowNum: 2},
	{Name: "Boron", Symbol: "B", AtomicNumber: 5, Group: 13, Period: 2, Category: "Metalloid", Color: "#3dbd90", ColNum: 13, RowNum: 2},
	{Name: "Carbon", Symbol: "C", AtomicNumber: 6, Group: 14, Period: 2, Category: "Nonmetal", Color: "#30c93d", ColNum: 14, RowNum: 2},
	{Name: "Nitrogen", Symbol: "N", AtomicNumber: 7, Group: 15, Period: 2, Category: "Nonmetal", Color: "#30c93d", ColNum: 15, RowNum: 2},
	{Name: "Oxygen", Symbol: "O", AtomicNumber: 8, Group: 16, Period: 2, Category: "Nonmetal", Color: "#30c93d", ColNum: 16, RowNum: 2},
	{Name: "Fluorine", Symbol: "F", AtomicNumber: 9, Group: 17, Period: 2, Category: "Nonmetal", Color: "#30c93d", ColNum: 17, RowNum: 2},
	{Name: "Neon", Symbol: "Ne", AtomicNumber: 10, Group: 18, Period: 2, Category: "Noble Gas", Color: "#06bbe8", ColNum: 18, RowNum: 2},
	{Name: "Sodium", Symbol: "Na", AtomicNumber: 11, Group: 1, Period: 3, Category: "Alkali Metal", Color: "#eda30e", ColNum: 1, RowNum: 3},
	{Name: "Magnesium", Symbol: "Mg", AtomicNumber: 12, Group: 2, Period: 3, Category: "Alkaline Earth Metal", Color: "#ed670e", ColNum: 2, RowNum: 3},
	{Name: "Aluminium", Symbol: "Al", AtomicNumber: 13, Group: 13, Period: 3, Category: "Post-transition Metal", Color: "#2181bb", ColNum: 13, RowNum: 3},
	{Name: "Silicon", Symbol: "Si", AtomicNumber: 14, Group: 14, Period: 3, Category: "Metalloid", Color: "#3dbd90", ColNum: 14, RowNum: 3},
	{Name: "Phosphorus", Symbol: "P", AtomicNumber: 15, Group: 15, Period: 3, Category: "Nonmetal", Color: "#30c93d", ColNum: 15, RowNum: 3},
	{Name: "Sulfur", Symbol: "S", AtomicNumber: 16, Group: 16, Period: 3, Category: "Nonmetal", Color: "#30c93d", ColNum: 16, RowNum: 3},
	{Name: "Chlorine", Symbol: "Cl", AtomicNumber: 17, Group: 17, Period: 3, Category: "Nonmetal", Color: "#30c93d", ColNum: 17, RowNum: 3},
	{Name: "Argon", Symbol: "Ar", AtomicNumber: 18, Group: 18, Period: 3, Category: "Noble Gas", Color: "#06bbe8", ColNum: 18, RowNum: 3},
	{Name: "Potassium", Symbol: "K", AtomicNumber: 19, Group: 1, Period: 4, Category: "Alkali Metal", Color: "#eda30e", ColNum: 1, RowNum: 4},
	{Name: "Calcium", Symbol: "Ca", AtomicNumber: 20, Group: 2, Period: 4, Category: "Alkaline Earth Metal", Color: "#ed670e", ColNum: 2, RowNum: 4},
	{Name: "Scandium", Symbol: "Sc", AtomicNumber: 21, Group: 3, Period: 4, Category: "Transition Metal", Color: "#dd1515", ColNum: 3, RowNum: 4},
	{Name: "Titanium", Symbol: "Ti", AtomicNumber: 22, Group: 4, Period: 4, Category: "Transition Metal", Color: "#dd1515", ColNum: 4, RowNum: 4},
	{Name: "Vanadium", Symbol: "V", AtomicNumber: 23, Group: 5, Period: 4, Category: "Transition Metal", Color: "#dd1515", ColNum: 5, RowNum: 4},
	{Name: "Chromium", Symbol: "Cr", AtomicNumber: 24, Group: 6, Period: 4, Category: "Transition Metal", Color: "#dd1515", ColNum: 6, RowNum: 4},
	{Name: "Manganese", Symbol: "Mn", AtomicNumber: 25, Group: 7, Period: 4, Category: "Transition Metal", Color: "#dd1515", ColNum: 7, RowNum: 4},
	{Name: "Iron", Symbol: "Fe", AtomicNumber: 26, Group: 8, Period: 4, Category: "Transition Metal", Color: "#dd1515", ColNum: 8, RowNum: 4},
	{Name: "Cobalt", Symbol: "Co", AtomicNumber: 27, Group: 9, Period: 4, Category: "Transition Metal", Color: "#dd1515", ColNum: 9, RowNum: 4},
	{Name: "Nickel", Symbol: "Ni", AtomicNumber: 28, Group: 10, Period: 4, Category: "Transition Metal", Color: "#dd1515", ColNum: 10, RowNum: 4},
	{Name: "Copper", Symbol: "Cu", AtomicNumber: 29, Group: 11, Period: 4, Category: "Transition Metal", Color: "#dd1515", ColNum: 11, RowNum: 4},
	{Name: "Zinc", Symbol: "Zn", AtomicNumber: 30, Group: 12, Period: 4, Category: "Transition Metal", Color: "#dd1515", ColNum: 12, RowNum: 4},
	{Name: "Gallium", Symbol: "Ga", AtomicNumber: 31, Group: 13, Period: 4, Category: "Post-transition Metal", Color: "#2181bb", ColNum: 13, RowNum: 4},
	{Name: "Germanium", Symbol: "Ge", AtomicNumber: 32, Group: 14, Period: 4, Category: "Metalloid", Color: "#3dbd90", ColNum: 14, RowNum: 4},
	{Name: "Arsenic", Symbol: "As", AtomicNumber: 33, Group: 15, Period: 4, Category: "Metalloid", Color: "#3dbd90", ColNum: 15, RowNum: 4},
	{Name: "Selenium", Symbol: "Se", AtomicNumber: 34, Group: 16, Period: 4, Category: "Nonmetal", Color: "#30c93d", ColNum: 16, RowNum: 4},
	{Name: "Bromine", Symbol: "Br", AtomicNumber: 35, Group: 17, Period: 4, Category: "Nonmetal", Color: "#30c93d", ColNum: 17, RowNum: 4},
	{Name: "Krypton", Symbol: "Kr", AtomicNumber: 36, Group: 18, Period: 4, Category: "Noble Gas", Color: "#06bbe8", ColNum: 18, RowNum: 4},
	{Name: "Rubidium", Symbol: "Rb", AtomicNumber: 37, Group: 1, Period: 5, Category: "Alkali Metal", Color: "#eda30e", ColNum: 1, RowNum: 5},
	{Name: "Strontium", Symbol: "Sr", AtomicNumber: 38, Group: 2, Period: 5, Category: "Alkaline Earth Metal", Color: "#ed670e", ColNum: 2, RowNum: 5},
	{Name: "Yttrium", Symbol: "Y", AtomicNumber: 39, Group: 3, Period: 5, Category: "Transition Metal", Color: "#dd1515", ColNum: 3, RowNum: 5},
	{Name: "Zirconium", Symbol: "Zr", AtomicNumber: 40, Group: 4, Period: 5, Category: "Transition Metal", Color: "#dd1515", ColNum: 4, RowNum: 5},
	{Name: "Niobium", Symbol: "Nb", AtomicNumber: 41, Group: 5, Period: 5, Category: "Transition Metal", Color: "#dd1515", ColNum: 5, RowNum: 5},
	{Name: "Molybdenum", Symbol: "Mo", AtomicNumber: 42, Group: 6, Period: 5, Category: "Transition Metal", Color: "#dd1515", ColNum: 6, RowNum: 5},
	{Name: "Technetium", Symbol: "Tc", AtomicNumber: 43, Group: 7, Period: 5, Category: "Transition Metal", Color: "#dd1515", ColNum: 7, RowNum: 5},
	{Name: "Ruthenium", Symbol: "Ru", AtomicNumber: 44, Group: 8, Period: 5, Category: "Transition Metal", Color: "#dd1515", ColNum: 8, RowNum: 5},
	{Name: "Rhodium", Symbol: "Rh", AtomicNumber: 45, Group: 9, Period: 5, Category: "Transition Metal", Color: "#dd1515", ColNum: 9, RowNum: 5},
	{Name: "Palladium", Symbol: "Pd", AtomicNumber: 46, Group: 10, Period: 5, Category: "Transition Metal", Color: "#dd1515", ColNum: 10, RowNum: 5},
	{Name: "Silver", Symbol: "Ag", AtomicNumber: 47, Group: 11, Period: 5, Category: "Transition Metal", Color: "#dd1515", ColNum: 11, RowNum: 5},
	{Name: "Cadmium", Symbol: "Cd", AtomicNumber: 48, Group: 12, Period: 5, Category: "Transition Metal", Color: "#dd1515", ColNum: 12, RowNum: 5},
	{Name: "Indium", Symbol: "In", AtomicNumber: 49, Group: 13, Period: 5, Category: "Post-transition Metal", Color: "#2181bb", ColNum: 13, RowNum: 5},
	{Name: "Tin", Symbol: "Sn", AtomicNumber: 50, Group: 14, Period: 5, Category: "Post-transition Metal", Color: "#2181bb", ColNum: 14, RowNum: 5},
	{Name: "Antimony", Symbol: "Sb", AtomicNumber: 51, Group: 15, Period: 5, Category: "Metalloid", Color: "#3dbd90", ColNum: 15, RowNum: 5},
	{Name: "Tellurium", Symbol: "Te", AtomicNumber: 52, Group: 16, Period: 5, Category: "Metalloid", Color: "#3dbd90", ColNum: 16, RowNum: 5},
	{Name: "Iodine", Symbol: "I", AtomicNumber: 53, Group: 17, Period: 5, Category: "Nonmetal", Color: "#30c93d", ColNum: 17, RowNum: 5},
	{Name: "Xenon", Symbol: "Xe", AtomicNumber: 54, Group: 18, Period: 5, Category: "Noble Gas", Color: "#06bbe8", ColNum: 18, RowNum: 5},
	{Name: "Cesium", Symbol: "Cs", AtomicNumber: 55, Group: 1, Period: 6, Category: "Alkali Metal", Color: "#eda30e", ColNum: 1, RowNum: 6},
	{Name: "Barium", Symbol: "Ba", AtomicNumber: 56, Group: 2, Period: 6, Category: "Alkaline Earth Metal", Color: "#ed670e", ColNum: 2, RowNum: 6},
	{Name: "Lanthanum", Symbol: "La", AtomicNumber: 57, Group: 3, Period: 6, Category: "Lanthanide", Color: "#ff7ea4", ColNum: 4, RowNum: 9},
	{Name: "Cerium", Symbol: "Ce", AtomicNumber: 58, Group: 3, Period: 6, Category: "Lanthanide", Color: "#ff7ea4", ColNum: 5, RowNum: 9},
	{Name: "Praseodymium", Symbol: "Pr", AtomicNumber: 59, Group: 3, Period: 6, Category: "Lanthanide", Color: "#ff7ea4", ColNum: 6, RowNum: 9},
	{Name: "Neodymium", Symbol: "Nd", AtomicNumber: 60, Group: 3, Period: 6, Category: "Lanthanide", Color: "#ff7ea4", ColNum: 7, RowNum: 9},
	{Name: "Promethium", Symbol: "Pm", AtomicNumber: 61, Group: 3, Period: 6, Category: "Lanthanide", Color: "#ff7ea4", ColNum: 8, RowNum: 9},
	{Name: "Samarium", Symbol: "Sm", AtomicNumber: 62, Group: 3, Period: 6, Category: "Lanthanide", Color: "#ff7ea4", ColNum: 9, RowNum: 9},
	{Name: "Europium", Symbol: "Eu", AtomicNumber: 63, Group: 3, Period: 6, Category: "Lanthanide", Color: "#ff7ea4", ColNum: 10, RowNum: 9},
	{Name: "Gadolinium", Symbol: "Gd", AtomicNumber: 64, Group: 3, Period: 6, Category: "Lanthanide", Color: "#ff7ea4", ColNum: 11, RowNum: 9},
	{Name: "Terbium", Symbol: "Tb", AtomicNumber: 65, Group: 3, Period: 6, Category: "Lanthanide", Color: "#ff7ea4", ColNum: 12, RowNum: 9},
	{Name: "Dysprosium", Symbol: "Dy", AtomicNumber: 66, Group: 3, Period: 6, Category: "Lanthanide", Color: "#ff7ea4", ColNum: 13, RowNum: 9},
	{Name: "Holmium", Symbol: "Ho", AtomicNumber: 67, Group: 3, Period: 6, Category: "Lanthanide", Color: "#ff7ea4", ColNum: 14, RowNum: 9},
	{Name: "Erbium", Symbol: "Er", AtomicNumber: 68, Group: 3, Period: 6, Category: "Lanthanide", Color: "#ff7ea4", ColNum: 15, RowNum: 9},
	{Name: "Thulium", Symbol: "Tm", AtomicNumber: 69, Group: 3, Period: 6, Category: "Lanthanide", Color: "#ff7ea4", ColNum: 16, RowNum: 9},
	{Name: "Ytterbium", Symbol: "Yb", AtomicNumber: 70, Group: 3, Period: 6, Category: "Lanthanide", Color: "#ff7ea4", ColNum: 17, RowNum: 9},
	{Name: "Lutetium", Symbol: "Lu", AtomicNumber: 71, Group: 3, Period: 6, Category: "Lanthanide", Color: "#ff7ea4", ColNum: 18, RowNum: 9},
	{Name: "Hafnium", Symbol: "Hf", AtomicNumber: 72, Group: 4, Period: 6, Category: "Transition Metal", Color: "#dd1515", ColNum: 4, RowNum: 6},
	{Name: "Tantalum", Symbol: "Ta", AtomicNumber: 73, Group: 5, Period: 6, Category: "Transition Metal", Color: "#dd1515", ColNum: 5, RowNum: 6},
	{Name: "Tungsten", Symbol: "W", AtomicNumber: 74, Group: 6, Period: 6, Category: "Transition Metal", Color: "#dd1515", ColNum: 6, RowNum: 6},
	{Name: "Rhenium", Symbol: "Re", AtomicNumber: 75, Group: 7, Period: 6, Category: "Transition Metal", Color: "#dd1515", ColNum: 7, RowNum: 6},
	{Name: "Osmium", Symbol: "Os", AtomicNumber: 76, Group: 8, Period: 6, Category: "Transition Metal", Color: "#dd1515", ColNum: 8, RowNum: 6},
	{Name: "Iridium", Symbol: "Ir", AtomicNumber: 77, Group: 9, Period: 6, Category: "Transition Metal", Color: "#dd1515", ColNum: 9, RowNum: 6},
	{Name: "Platinum", Symbol: "Pt", AtomicNumber: 78, Group: 10, Period: 6, Category: "Transition Metal", Color: "#dd1515", ColNum: 10, RowNum: 6},
	{Name: "Gold", Symbol: "Au", AtomicNumber: 79, Group: 11, Period: 6, Category: "Transition Metal", Color: "#dd1515", ColNum: 11, RowNum: 6},
	{Name: "Mercury", Symbol: "Hg", AtomicNumber: 80, Group: 12, Period: 6, Category: "Transition Metal", Color: "#dd1515", ColNum: 12, RowNum: 6},
	{Name: "Thallium", Symbol: "Tl", AtomicNumber: 81, Group: 13, Period: 6, Category: "Post-transition Metal", Color: "#2181bb", ColNum: 13, RowNum: 6},
	{Name: "Lead", Symbol: "Pb", AtomicNumber: 82, Group: 14, Period: 6, Category: "Post-transition Metal", Color: "#2181bb", ColNum: 14, RowNum: 6},
	{Name: "Bismuth", Symbol: "Bi", AtomicNumber: 83, Group: 15, Period: 6, Category: "Post-transition Metal", Color: "#2181bb", ColNum: 15, RowNum: 6},
	{Name: "Polonium", Symbol: "Po", AtomicNumber: 84, Group: 16, Period: 6, Category: "Post-transition Metal", Color: "#2181bb", ColNum: 16, RowNum: 6},
	{Name: "Astatine", Symbol: "At", AtomicNumber: 85, Group: 17, Period: 6, Category: "Metalloid", Color: "#3dbd90", ColNum: 17, RowNum: 6},
	{Name: "Radon", Symbol: "Rn", AtomicNumber: 86, Group: 18, Period: 6, Category: "Noble Gas", Color: "#06bbe8", ColNum: 18, RowNum: 6},
	{Name: "Francium", Symbol: "Fr", AtomicNumber: 87, Group: 1, Period: 7, Category: "Alkali Metal", Color: "#eda30e", ColNum: 1, RowNum: 7},
	{Name: "Radium", Symbol: "Ra", AtomicNumber: 88, Group: 2, Period: 7, Category: "Alkaline Earth Metal", Color: "#ed670e", ColNum: 2, RowNum: 7},
	{Name: "Actinium", Symbol: "Ac", AtomicNumber: 89, Group: 3, Period: 7, Category: "Actinide", Color: "#e95ec2", ColNum: 4, RowNum: 10},
	{Name: "Thorium", Symbol: "Th", AtomicNumber: 90, Group: 3, Period: 7, Category: "Actinide", Color: "#e95ec2", ColNum: 5, RowNum: 10},
	{Name: "Protactinium", Symbol: "Pa", AtomicNumber: 91, Group: 3, Period: 7, Category: "Actinide", Color: "#e95ec2", ColNum: 6, RowNum: 10},
	{Name: "Uranium", Symbol: "U", AtomicNumber: 92, Group: 3, Period: 7, Category: "Actinide", Color: "#e95ec2", ColNum: 7, RowNum: 10},
	{Name: "Neptunium", Symbol: "Np", AtomicNumber: 93, Group: 3, Period: 7, Category: "Actinide", Color: "#e95ec2", ColNum: 8, RowNum: 10},
	{Name: "Plutonium", Symbol: "Pu", AtomicNumber: 94, Group: 3, Period: 7, Category: "Actinide", Color: "#e95ec2", ColNum: 9, RowNum: 10},
	{Name: "Americium", Symbol: "Am", AtomicNumber: 95, Group: 3, Period: 7, Category: "Actinide", Color: "#e95ec2", ColNum: 10, RowNum: 10},
	{Name: "Curium", Symbol: "Cm", AtomicNumber: 96, Group: 3, Period: 7, Category: "Actinide", Color: "#e95ec2", ColNum: 11, RowNum: 10},
	{Name: "Berkelium", Symbol: "Bk", AtomicNumber: 97, Group: 3, Period: 7, Category: "Actinide", Color: "#e95ec2", ColNum: 12, RowNum: 10},
	{Name: "Californium", Symbol: "Cf", AtomicNumber: 98, Group: 3, Period: 7, Category: "Actinide", Color: "#e95ec2", ColNum: 13, RowNum: 10},
	{Name: "Einsteinium", Symbol: "Es", AtomicNumber: 99, Group: 3, Period: 7, Category: "Actinide", Color: "#e95ec2", ColNum: 14, RowNum: 10},
	{Name: "Fermium", Symbol: "Fm", AtomicNumber: 100, Group: 3, Period: 7, Category: "Actinide", Color: "#e95ec2", ColNum: 15, RowNum: 10},
	{Name: "Mendelevium", Symbol: "Md", AtomicNumber: 101, Group: 3, Period: 7, Category: "Actinide", Color: "#e95ec2", ColNum: 16, RowNum: 10},
	{Name: "Nobelium", Symbol: "No", AtomicNumber: 102, Group: 3, Period: 7, Category: "Actinide", Color: "#e95ec2", ColNum: 17, RowNum: 10},
	{Name: "Lawrencium", Symbol: "Lr", AtomicNumber: 103, Group: 3, Period: 7, Category: "Actinide", Color: "#e95ec2", ColNum: 18, RowNum: 10},
	{Name: "Rutherfordium", Symbol: "Rf", AtomicNumber: 104, Group: 4, Period: 7, Category: "Transition Metal", Color: "#dd1515", ColNum: 4, RowNum: 7},
	{Name: "Dubnium", Symbol: "Db", AtomicNumber: 105, Group: 5, Period: 7, Category: "Transition Metal", Color: "#dd1515", ColNum: 5, RowNum: 7},
	{Name: "Seaborgium", Symbol: "Sg", AtomicNumber: 106, Group: 6, Period: 7, Category: "Transition Metal", Color: "#dd1515", ColNum: 6, RowNum: 7},
	{Name: "Bohrium", Symbol: "Bh", AtomicNumber: 107, Group: 7, Period: 7, Category: "Transition Metal", Color: "#dd1515", ColNum: 7, RowNum: 7},
	{Name: "Hassium", Symbol: "Hs", AtomicNumber: 108, Group: 8, Period: 7, Category: "Transition Metal", Color: "#dd1515", ColNum: 8, RowNum: 7},
	{Name: "Meitnerium", Symbol: "Mt", AtomicNumber: 109, Group: 9, Period: 7, Category: "Unknown", Color: "#888888", ColNum: 9, RowNum: 7},
	{Name: "Darmstadtium", Symbol: "Ds", AtomicNumber: 110, Group: 10, Period: 7, Category: "Unknown", Color: "#888888", ColNum: 10, RowNum: 7},
	{Name: "Roentgenium", Symbol: "Rg", AtomicNumber: 111, Group: 11, Period: 7, Category: "Unknown", Color: "#888888", ColNum: 11, RowNum: 7},
	{Name: "Copernicium", Symbol: "Cn", AtomicNumber: 112, Group: 12, Period: 7, Category: "Transition Metal", Color: "#dd1515", ColNum: 12, RowNum: 7},
	{Name: "Nihonium", Symbol: "Nh", AtomicNumber: 113, Group: 13, Period: 7, Category: "Unknown", Color: "#888888", ColNum: 13, RowNum: 7},
	{Name: "Flerovium", Symbol: "Fl", AtomicNumber: 114, Group: 14, Period: 7, Category: "Post-transition Metal", Color: "#2181bb", ColNum: 14, RowNum: 7},
	{Name: "Moscovium", Symbol: "Mc", AtomicNumber: 115, Group: 15, Period: 7, Category: "Unknown", Color: "#888888", ColNum: 15, RowNum: 7},
	{Name: "Livermorium", Symbol: "Lv", AtomicNumber: 116, Group: 16, Period: 7, Category: "Unknown", Color: "#888888", ColNum: 16, RowNum: 7},
	{Name: "Tennessine", Symbol: "Ts", AtomicNumber: 117, Group: 17, Period: 7, Category: "Unknown", Color: "#888888", ColNum: 17, RowNum: 7},
	{Name: "Oganesson", Symbol: "Og", AtomicNumber: 118, Group: 18, Period: 7, Category: "Unknown", Color: "#888888", ColNum: 18, RowNum: 7},
}
